### ISSUE TITLE
Data on Dropbox, Code on Github

### ISSUE THREAD

**Issue by nadialucas** [nadialucas/tom_epic_task#7]
Since no data should ever live on the github, it was totally reasonable that you guys put your data/output on your local machines since I wasn't super clear about exactly how we want to organize this. 

Just because I hate Dropbox for code, doesn't mean it's not useful! So what I want you guys to do is move the data you downloaded (perhaps change the destination filepath in the webscraper as well) to the right DB folder with your name on it and then change all filepaths such that both of us can just checkout code and run straight from our local machines:

 - [ ] Take out a new branch once your current working code is in a good place for this to happen
 - [ ] Move all raw data to a folder titled "RawData" in your respective Dropbox folders
 - [ ] Change all the analysis such that all output data goes into a folder titled "IntermediateData"  in your respective DB folder
 - [ ] Change all hardcoded folder names such that when I run any of your code, all I need to do is pull your branch and run it on my computer, not needing to touch any of your code. My Dropbox filepath is "/Users/nadialucas/Dropbox". You should only need to set this one time at the beginning of every code file. Talk to me if you are spending a lot of time trying to figure this out, it should be a quick fix.
      - [ ] Make sure I can run the webscraper as well, my personl chromedriver path is "/Users/nadialucas/anaconda/bin/chromedriver"
 - [ ] Make two folders in the repo, one titled "Build" and one titled "Analysis". Store your code respectively in these folders. If we get to the writeup, you'll need to make a third folder called "Paper".

Any questions you have about folders and best organizational practices can probably be answered by this [page](https://github.com/kelloggrk/Kellogg_RA_Manual/wiki/Folder-Organization) in Ryan's wiki, aka the bible of how to be a perfect RA.

**Comment by TomBearpark** [comment]
Changes made (hopefully)!
